### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by KyronSr** [gdsestimating/vb6-install-recipe#1]
`if ($extractedFromIso) {
    Write-Host "Cleaning up vb6 install files"
    Remove-Item -Path $sp6SourceDir -Force -Recurse
}
`
should be
`if ($extractedFromIso) {
    Write-Host "Cleaning up vb6 install files"
    Remove-Item -Path $vb6SourceDir -Force -Recurse
}
`

If you have an MSDN license, you can download the required files from MS -- Might also be worth noting that you can download the VB6 Iso from 
https://my.visualstudio.com/Downloads?q=Visual%20Basic%206.0%20Enterprise

And the "service pack 6 iso" from
https://my.visualstudio.com/Downloads?q=Visual%20Basic%206.0%20Service%20Pack%206
but you need to extract the vs6sp6B.exe from that ISO

But THANKS -- this one worked, once I used the original ISO files instead of some random files I had laying around.

**Comment by bzuillsmith** [comment]
Thanks for pointing out the bug! I think you got an early version of the repo before I flushed out the readme a little more. It already mentions downloading it from my.visualstudio.com, though not with the specific query strings.

So glad it worked for you. Nice to see people find it useful!
